#! /bin/sh

#    _
#   | |__  ___ _ ____      ___ __ ___
#   | '_ \/ __| '_ \ \ /\ / / '_ ` _ \
#   | |_) \__ \ |_) \ V  V /| | | | | |
#   |_.__/|___/ .__/ \_/\_/ |_| |_| |_|
#             |_|
#
# By Sayujya Apte (2025)


pgrep -x sxhkd > /dev/null || sxhkd &
pgrep -x picom > /dev/null || picom &
$HOME/.config/polybar/launch.sh &
feh --no-fehbg --bg-fill /usr/share/backgrounds/windows-xp.jpg &
bspc monitor -d I II III IV V VI VII VIII IX X

bspc config border_width         2
bspc config window_gap           8

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc config normal_border_color "#181825"
bspc config focused_border_color "#89b4fa"

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off

